 export let videos = [
  { 
    id: 1,
    miniatura: "../miniaturas/1.jpg",
    icono: "../canal/1.jpg",
    Ncanal:"@pixter",
    video: "../videos/1.mp4",
    Titulo: "Jhin full robo de vida 100% ",
    Vistas: "1.450.031 vistas",
    Fechas:"Hace 3 meses",
    Category:"Diseño UX",
    Todos:"Todos",
  },
  { 
    id: 2,
    miniatura:"../miniaturas/2.jpg",
    icono:"../canal/2.jpg",
    Ncanal:"@Gorillaz",
    video:"../videos/2.mp4",
    Titulo:"FEEL GOOD.INC ",
    Vistas:"6.670.000 vistas",
    Fechas: "Hace 2 años",
    Category:"Musica",
  },
  { 
    id:3 ,
    miniatura:"../miniaturas/3.jpg",
    icono:"../canal/3.jpg",
    Ncanal:"@Reddit",
    video:"../videos/3.mp4",
    Titulo:"REDDIT ULTIMO EVENTO (OMG)",
    Vistas:"2.050.000 vistas",
    Fechas: "Hace unos dias",
    Category:"Programacion",
    Todos:"Todos",
  },
  { 
    id:4 ,
    miniatura:"../miniaturas/4.jpg",
    icono:"../canal/4.jpg",
    Ncanal:"@Ramms",
    video:"../videos/4.mp4",
    Titulo:"Rammstein-Du hast (Official)",
    Vistas:"8.900.000 vistas",
    Fechas: "Hace 2 dias",
    Category:"Musica",
    Todos:"Todos",
  },
  { 
    id:5 ,
    miniatura:"../miniaturas/5.jpg",
    icono:"../canal/5.jpg",
    Ncanal:"@Faker",
    video:"../videos/5.mp4",
    Titulo:"FAKER VOLVIO?el mejor mid..",
    Vistas:"1.222.000 vistas",
    Fechas: "Hace 3años",
    Category:"Diseño UX",
    Todos:"Todos",
  },
  { 
    id:6 ,
    miniatura:"../miniaturas/6.jpg",
    icono:"../canal/6.jpg",
    Ncanal:"@HistorM",
    Video:"",
    Titulo:"TOP 7 VIDEOS DE TERROR",
    Vistas:"1.356.541 vistas",
    Fechas: "Hace 2 años",
    Category:"Diseño UX",
    Todos:"Todos",
  },
  { 
    id:7 ,
    miniatura:"../miniaturas/7.jpg",
    icono:"../canal/6.jpg",
    Ncanal:"@HistorM",
    Video:"",
    Titulo:"7 datos deep web",
    Vistas:"4.326.800 vistas",
    Fechas: "Hace 4 años",
    Category:"Diseño UX",
    Todos:"Todos",
  },
  { 
    id:8 ,
    miniatura:"../miniaturas/8.jpg",
    icono:"../canal/7.jpg",
    Ncanal:"@Music1",
    Video:"",
    Titulo:"7 CASOS DE TERROR",
    Vistas:"8.326.200 vistas",
    Fechas: "Hace 1 año",
    Category:"Diseño UX",
    Todos:"Todos",
    
  },
  { 
    id:9 ,
    miniatura:"../miniaturas/9.jpg",
    icono:"../canal/12.jpg",
    Ncanal:"@Vevo2",
    Video:"",
    Titulo:"KARMALAND",
    Vistas:"8.326.200 vistas",
    Fechas: "Hace 10 años",
    Category:"Diseño UX",
    Todos:"Todos",
  
  },
  { 
    id:10 ,
    miniatura:"../miniaturas/10.jpg",
    icono:"../canal/10.jpg",
    Ncanal:"@rasta1",
    Video:"",
    Titulo:"TUTORIAL MINIATURAS",
    Vistas:"800 vistas",
    Fechas: "Hace 4 años",
    Category:"Diseño UX",
    Todos:"Todos",
  },
  { 
    id:11 ,
    miniatura:"../miniaturas/11.jpg",
    icono:"../canal/12.jpg",
    Ncanal:"@Vevo2",
    Video:"",
    Titulo:"EL VIDEO ESPERADO",
    Vistas:"6.200 vistas",
    Fechas: "Hace  2 años",
    Category:"Musica",
    Todos:"Todos",
  },
  { 
    id:12 ,
    miniatura:"../miniaturas/12.jpg",
    icono:"../canal/8.jpg",
    Ncanal:"@Youtru",
    Video:"",
    Titulo:"VALORANT AL 10",
    Vistas:"1.900.541 vistas",
    Fechas: "Hace 1 año",
    Category:"Diseño UX",
    Todos:"Todos",
  },
  { 
    id:13 ,
    miniatura:"../miniaturas/13.jpg",
    icono:"../canal/9.jpg",
    Ncanal:"ztur",
    Video:"",
    Titulo:"YOUTUBE?",
    Vistas:"2.826.200 vistas",
    Fechas: "Hace 4 años",
    Category:"Musica",
    Todos:"Todos",
  },
  { 
    id:14 ,
    miniatura:"../miniaturas/14.jpg",
    icono:"../canal/10.jpg",
    Ncanal:"@rasta1",
    Video:"",
    Titulo:"TRANSFORMACION DE 10",
    Vistas:"1.326.200 vistas",
    Fechas: "Hace 1 año",
    Category:"Diseño UX",
    Todos:"Todos",
  },
  { 
    id:15 ,
    miniatura:"../miniaturas/15.jpg",
    icono:"../canal/11.jpg",
    Ncanal:"@Vevo20",
    Video:"",
    Titulo:"HAZLO EFICIENTE EN LA WEB",
    Vistas:"22.926.200 vistas",
    Fechas: "Hace 3 meses",
    Category:"Programacion",
    Todos:"Todos",
    
  },
  { 
    id:16,
    miniatura:"../miniaturas/16.jpg",
    icono:"../canal/9.jpg",
    Ncanal:"@ztur",
    Video:"",
    Titulo:"BUSCALO YA internet",
    Vistas:"5.826.210 vistas",
    Fechas: "Hace 2 meses",
    Category:"Diseño UX",
    Todos:"Todos",
  },
  { 
    id:17,
    miniatura:"../miniaturas/18.jpg",
    icono:"../canal/11.jpg",
    Ncanal:"@Vevo20",
    Video:"",
    Titulo:"PROGRAMACION",
    Vistas:"1.356.220 vistas",
    Fechas: "Hace 1 año",
    Category:"Programacion",
    Todos:"Todos",
  },
  { 
    id:18,
    miniatura:"../miniaturas/19.jpg",
    icono:"../canal/8.jpg",
    Ncanal:"@Youtru",
    Video:"",
    Titulo:"WEB SITES QUE TE SERVIRAN",
    Vistas:"10.000.000 vistas",
    Fechas: "Hace 2 años",
    Category:"Diseño UX",
    Todos:"Todos",
  },
  { 
    id:19,
    miniatura:"../miniaturas/20.jpg",
    icono:"../canal/10.jpg",
    Ncanal:"@rasta1",
    Video:"",
    Titulo:"PODCAST BUSCALO YA",
    Vistas:"52.120.200 vistas",
    Fechas: "Hace 4 años",
    Category:"Musica",
  },
  { 
    id:20,
    miniatura:"../miniaturas/21.jpg",
    icono:"../canal/7.jpg",
    Ncanal:"@Music1",
    Video:"",
    Titulo:"BEST TRAP 2022",
    Vistas:"122.006.200 vistas",
    Fechas: "Hace 1 año",
    Category:"Musica",
    Todos:"Todos",
  },
  { 
    id:21,
    miniatura:"../miniaturas/22.jpg",
    icono:"../canal/8.jpg",
    Ncanal:"@Youtru",
    Video:"",
    Titulo:"PARTY MUSIC",
    Vistas:"12.126.200 vistas",
    Fechas: "Hace 3 meses",
    Category:"Musica",
    Todos:"Todos",
  },
  { id:22,
    miniatura:"../miniaturas/23.jpg",
    icono:"../canal/6.jpg",
    Ncanal:"@HistorM",
    Video:"",
    Titulo:"HOUSE MUSIC",
    Vistas:"5.626.200 vistas",
    Fechas: "Hace 3 dias",
    Category:"Musica",
    Todos:"Todos",
  },
  { 
    id:23,
    miniatura:"../miniaturas/24.jpg",
    icono:"../canal/6.jpg",
    Ncanal:"@HistorM",
    Video:"",
    Titulo:"PROGRAMACION RAPIDA",
    Vistas:"200.816.200 vistas",
    Fechas: "Hace 3 meses",
    Category:"Programacion",
    Todos:"Todos",
  },
  { 
    id:24,
    miniatura:"../miniaturas/25.jpg",
    icono:"../canal/9.jpg",
    Ncanal:"@ztur",
    Video:"",
    Titulo:"PARADIGMA DE AZUCAR",
    Vistas:"4.356.541 vistas",
    Fechas: "Hace 2 dias",
    Category:"Diseño UX",
    Todos:"Todos",
  },
  { 
    id:25,
    miniatura:"../miniaturas/26.jpg",
    icono:"../canal/11.jpg",
    Ncanal:"@Vevo20",
    Video:"",
    Titulo:"APRENDE RAPIDO LA PROGRAMACION",
    Vistas:"200 vistas",
    Fechas: "Hace 1 dia",
    Category:"Programacion",
    Todos:"Todos",
  },
  { 
    id:26,
    miniatura:"../miniaturas/27.jpg",
    icono:"../canal/8.jpg",
    Ncanal:"@Youtru",
    Video:"",
    Titulo:"WEB SITES",
    Vistas:"2.326 vistas",
    Fechas: "Hace 2 meses",
    Category:"Programacion",
    Todos:"Todos",

  },
  { 
    id:27,
    miniatura:"../miniaturas/28.jpg",
    icono:"../canal/3.jpg",
    Ncanal:"@blur",
    Video:"",
    Titulo:"WORDPRESS",
    Vistas:"12.726.260 vistas",
    Fechas: "Hace 1 año",
    Category:"Diseño UX",
    Todos:"Todos",
  },
  { 
    id:28,
    miniatura:"../miniaturas/29.jpg",
    icono:"../canal/10.jpg",
    Ncanal:"@rasta1",
    Video:"",
    Titulo:"WORDPRESS SEGUNDA PARTE",
    Vistas:"9.626.200 vistas",
    Fechas: "Hace 2 años",
    Category:"Diseño UX",
    Todos:"Todos",
  },
  { 
    id:29,
    miniatura:"../miniaturas/30.jpg",
    icono:"../canal/7.jpg",
    Ncanal:"@Music1",
    Video:"",
    Titulo:"ACB",
    Vistas:"2.326.200 vistas",
    Fechas: "Hace 1 mes",
    Category:"Musica",
    Todos:"Todos",
  },
]
